const express=require('express'),path=require('path'),fs=require('fs'),crypto=require('crypto'),rateLimit=require('express-rate-limit');
let OpenAI;try{OpenAI=require('openai').default||require('openai')}catch{}
const app=express(),PORT=process.env.PORT||3000,DATA=path.join(__dirname,'data'),DB=path.join(DATA,'db.json');
fs.mkdirSync(DATA,{recursive:true});
const isRender=Boolean(process.env.RENDER);
if(isRender && !process.env.ADMIN_PASSWORD) throw new Error('ADMIN_PASSWORD must be set in Render Environment Variables before deployment.');
if(isRender && process.env.ADMIN_PASSWORD.length < 12) throw new Error('ADMIN_PASSWORD must be at least 12 characters in Render Environment Variables.');
let db;try{db=JSON.parse(fs.readFileSync(DB))}catch{db={users:[],schedules:[],announcements:[],tasks:[]};save()}
function save(){fs.writeFileSync(DB+'.tmp',JSON.stringify(db));fs.renameSync(DB+'.tmp',DB)} function id(p){return p+'_'+crypto.randomBytes(6).toString('hex')} function today(){return new Date().toISOString().slice(0,10)}
function pw(p){let s=crypto.randomBytes(16).toString('hex');return s+'.'+crypto.scryptSync(p,s,64).toString('hex')}function okpw(p,x){let [s,h]=(x||'').split('.');if(!s||!h)return false;return crypto.timingSafeEqual(Buffer.from(h,'hex'),crypto.scryptSync(p,s,64))}function clean(u){return{id:u.id,name:u.name,username:u.username,role:u.role,xp:u.xp,level:u.level,streak:u.streak,badges:u.badges||[],lastCheckin:u.lastCheckin,aiToday:u.aiDate===today()?u.aiCount:0}}
function auth(req,res,next){let t=(req.headers.authorization||'').replace('Bearer ','');let u=db.users.find(x=>x.token===t);if(!u)return res.status(401).json({error:'Vui lòng đăng nhập'});req.user=u;next()}function admin(req,res,next){if(req.user.role!=='admin')return res.status(403).json({error:'Chỉ Admin mới có quyền'});next()}function xp(u,n){u.xp=Math.max(0,u.xp+n);u.level=1+Math.floor(u.xp/250)}
if(!db.users.some(x=>x.role==='admin')){db.users.push({id:id('usr'),name:'7A6 Admin',username:process.env.ADMIN_USER||'admin',password:pw(process.env.ADMIN_PASSWORD||'change-me-now'),role:'admin',xp:0,level:1,streak:0,lastCheckin:null,badges:['founder'],aiCount:0,aiDate:today(),token:null});save()}
app.disable('x-powered-by');
app.use((q,r,next)=>{r.setHeader('X-Content-Type-Options','nosniff');r.setHeader('Referrer-Policy','strict-origin-when-cross-origin');next()});
app.use(rateLimit({windowMs:60000,max:120,standardHeaders:true,legacyHeaders:false}));app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'public')));
app.get('/health',(q,r)=>r.json({ok:true,service:'7A6 Study Bot'}));
app.post('/api/register',(q,r)=>{let{name,username,password}=q.body;if(!name||!username||!password||password.length<6)return r.status(400).json({error:'Vui lòng điền đủ thông tin; mật khẩu ít nhất 6 ký tự'});if(db.users.some(x=>x.username.toLowerCase()===username.toLowerCase()))return r.status(409).json({error:'Tài khoản đã tồn tại'});let u={id:id('usr'),name:String(name).slice(0,40),username:String(username).slice(0,30),password:pw(password),role:'student',xp:0,level:1,streak:0,lastCheckin:null,badges:['newbie'],aiCount:0,aiDate:today(),token:crypto.randomBytes(32).toString('hex'),done:[]};db.users.push(u);save();r.json({token:u.token,user:clean(u)})});
app.post('/api/login',(q,r)=>{let u=db.users.find(x=>x.username.toLowerCase()===String(q.body.username||'').toLowerCase());if(!u||!okpw(String(q.body.password||''),u.password))return r.status(401).json({error:'Sai tài khoản hoặc mật khẩu'});u.token=crypto.randomBytes(32).toString('hex');save();r.json({token:u.token,user:clean(u)})});app.post('/api/logout',auth,(q,r)=>{q.user.token=null;save();r.json({ok:true})});app.get('/api/me',auth,(q,r)=>r.json(clean(q.user)));
app.post('/api/checkin',auth,(q,r)=>{if(q.user.lastCheckin===today())return r.status(400).json({error:'Bạn đã điểm danh hôm nay'});let y=new Date(Date.now()-86400000).toISOString().slice(0,10);q.user.streak=q.user.lastCheckin===y?q.user.streak+1:1;q.user.lastCheckin=today();xp(q.user,25);if(q.user.streak>=7&&!q.user.badges.includes('week'))q.user.badges.push('week');save();r.json({message:'+25 XP · Điểm danh thành công',user:clean(q.user)})});
app.get('/api/dashboard',auth,(q,r)=>{let d=today();r.json({user:clean(q.user),schedules:db.schedules.filter(x=>x.active!==false&&x.date>=d).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).slice(0,10),announcements:db.announcements.filter(x=>x.active!==false).sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).slice(0,8),tasks:db.tasks.filter(x=>x.active!==false),leaders:db.users.filter(x=>x.role==='student').sort((a,b)=>b.xp-a.xp).slice(0,10).map(clean)})});
app.post('/api/tasks/:id/complete',auth,(q,r)=>{let t=db.tasks.find(x=>x.id===q.params.id);if(!t)return r.status(404).json({error:'Không tìm thấy nhiệm vụ'});q.user.done=q.user.done||[];let k=t.id+':'+today();if(q.user.done.includes(k))return r.status(400).json({error:'Đã hoàn thành nhiệm vụ hôm nay'});q.user.done.push(k);xp(q.user,Number(t.xp)||10);save();r.json({message:`+${t.xp} XP`,user:clean(q.user)})});app.get('/api/leaderboard',auth,(q,r)=>r.json(db.users.filter(x=>x.role==='student').sort((a,b)=>b.xp-a.xp).map(clean).slice(0,50)));
const ail=rateLimit({windowMs:60000,max:8,message:{error:'Bạn đang gửi quá nhanh. Chờ một chút nhé.'}});app.post('/api/ai',auth,ail,async(q,r)=>{if(!OpenAI||!process.env.OPENAI_API_KEY)return r.status(503).json({error:'AI chưa được cấu hình trên server'});if(q.user.aiDate!==today()){q.user.aiDate=today();q.user.aiCount=0}if(q.user.aiCount>=30)return r.status(429).json({error:'Bạn đã dùng 30 lượt AI hôm nay'});let m=String(q.body.message||'').trim().slice(0,5000);if(!m)return r.status(400).json({error:'Hãy nhập câu hỏi'});q.user.aiCount++;save();try{let c=new OpenAI({apiKey:process.env.OPENAI_API_KEY}),z=await c.responses.create({model:process.env.OPENAI_MODEL||'gpt-5.6-luna',instructions:'Bạn là 7A6 Study Bot, trợ lý học tập cho học sinh THCS. Giải thích dễ hiểu, có bước làm, khuyến khích tự suy nghĩ. Không làm bài kiểm tra thay học sinh.',input:m});xp(q.user,5);save();r.json({answer:z.output_text||'Chưa có câu trả lời.',user:clean(q.user)})}catch(e){r.status(500).json({error:'AI đang bận, hãy thử lại sau'})}});
app.use('/api/admin',auth,admin);app.get('/api/admin/stats',(q,r)=>r.json({users:db.users.filter(x=>x.role==='student').length,schedules:db.schedules.length,announcements:db.announcements.length,tasks:db.tasks.length}));
app.post('/api/admin/schedules',(q,r)=>{let b=q.body;if(!b.title||!b.date)return r.status(400).json({error:'Thiếu tiêu đề hoặc ngày'});let x={id:id('sch'),title:String(b.title).slice(0,100),subject:String(b.subject||'').slice(0,40),date:b.date,time:String(b.time||''),room:String(b.room||''),teacher:String(b.teacher||''),note:String(b.note||'').slice(0,300),createdAt:new Date().toISOString(),active:true};db.schedules.push(x);save();r.json(x)});app.delete('/api/admin/schedules/:id',(q,r)=>{db.schedules=db.schedules.filter(x=>x.id!==q.params.id);save();r.json({ok:true})});
app.post('/api/admin/announcements',(q,r)=>{let b=q.body;if(!b.title||!b.body)return r.status(400).json({error:'Thiếu tiêu đề hoặc nội dung'});let x={id:id('ann'),title:String(b.title).slice(0,120),body:String(b.body).slice(0,1000),type:b.type||'info',createdAt:new Date().toISOString(),active:true};db.announcements.push(x);save();r.json(x)});app.delete('/api/admin/announcements/:id',(q,r)=>{db.announcements=db.announcements.filter(x=>x.id!==q.params.id);save();r.json({ok:true})});
app.post('/api/admin/tasks',(q,r)=>{let b=q.body;if(!b.title)return r.status(400).json({error:'Thiếu tên nhiệm vụ'});let x={id:id('task'),title:String(b.title).slice(0,120),xp:Math.min(100,Math.max(1,Number(b.xp)||10)),createdAt:new Date().toISOString(),active:true};db.tasks.push(x);save();r.json(x)});app.delete('/api/admin/tasks/:id',(q,r)=>{db.tasks=db.tasks.filter(x=>x.id!==q.params.id);save();r.json({ok:true})});
app.get('/api/admin/users',(q,r)=>r.json(db.users.filter(x=>x.role==='student').map(clean)));app.post('/api/admin/users/:id/xp',(q,r)=>{let u=db.users.find(x=>x.id===q.params.id);if(!u)return r.status(404).json({error:'Không tìm thấy'});xp(u,Math.max(-1000,Math.min(1000,Number(q.body.xp)||0)));save();r.json(clean(u))});app.get('/{*splat}',(q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,'0.0.0.0',()=>console.log('7A6 Study Bot V1 PRO on '+PORT));
